- name: deploy anubis apache reverse proxy config
  template:
    src: reverse-proxy.conf
    dest: /etc/apache2/madek/conf.d/madek_895_anubis.conf
    mode: 0644
  when: anubis_enabled
  register: anubis_proxy_deployed

- name: remove anubis apache reverse proxy config
  file:
    path: /etc/apache2/madek/conf.d/madek_895_anubis.conf
    state: absent
  when: not anubis_enabled
  register: anubis_proxy_removed

- name: reload reverse-proxy for anubis
  service:
    name: apache2
    state: reloaded
  when: anubis_proxy_deployed.changed or anubis_proxy_removed.changed
