- name: reload systemd
  systemd:
    daemon_reload: yes

- name: enable and start anubis service
  service:
    name: anubis@madek
    state: started
    enabled: yes

- name: restart anubis if config changed
  service:
    name: anubis@madek
    state: restarted
  when: anubis_env_config.changed or anubis_bot_policies.changed
